### ISSUE TITLE
Location Search Excel Export

### ISSUE THREAD

**Issue by amberehall** [gaepdit/FMS#327]
Should only the results from the search be exported?  1 item shows on the map, but the export has 7 records

Facility Search on exports what is in the results.

**Comment by amberehall** [comment]
[FMS_Phase2_Testing_Location_Search_Excel_Export.docx](https://github.com/gaepdit/FMS/files/14285585/FMS_Phase2_Testing_Location_Search_Excel_Export.docx)

Screenshots attached

**Comment by tom-karasch** [comment]
Thanks, I have not modified any reporting yet. It is next task on my list after Layout issues/enhancements

**Comment by tom-karasch** [comment]
Please copy and paste screenshots directly in edit space in GitHub. Word Docs have to be downloaded and opened, and don't maintain good resolution. Thanks

Report is fixed

**Comment by amberehall** [comment]
still showing more than what is in the search results.  the results only had the 3 RNs in the screenshot.  report shows more than RN.  if that is how it is supposed to work that is fine, just let me know.

![Image](https://github.com/gaepdit/FMS/assets/148375928/5e15d409-f368-406d-9eb3-600c983854c3)

**Comment by amberehall** [comment]
Location Excel Export functions properly and with the correct numbers of rows
